//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnevnik
    {
        public int id_dnevnik { get; set; }
        public Nullable<int> id_ychenik { get; set; }
        public Nullable<int> id_predmet { get; set; }
        public Nullable<int> osenka { get; set; }
    
        public virtual predmet predmet { get; set; }
        public virtual ycheniki ycheniki { get; set; }
    }
}
