//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class opt_rab
    {
        public int id_opt_rab { get; set; }
        public Nullable<int> id_prepod { get; set; }
        public Nullable<int> goda { get; set; }
    
        public virtual prepod prepod { get; set; }
    }
}
