//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class prepod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prepod()
        {
            this.opt_rab = new HashSet<opt_rab>();
        }
    
        public int id_prepod { get; set; }
        public string fam { get; set; }
        public string ima { get; set; }
        public string otchectvo { get; set; }
        public Nullable<int> id_predmet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<opt_rab> opt_rab { get; set; }
        public virtual predmet predmet { get; set; }
    }
}
