//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ycheb_chas
    {
        public int id_ycheb_chas { get; set; }
        public Nullable<int> id_predmet { get; set; }
        public Nullable<int> kolva_chasov { get; set; }
    
        public virtual predmet predmet { get; set; }
    }
}
